# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-KR
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
  languageCode: en-US
  contentDir: content/en
  title: English Website..?
  params:
    description: Site description in English
  menu:
    main:
      - name: 소개
        url: '#about'
        weight: 2
