# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-KR
  languageName: "한국어"
  contentDir:content/ko
  weight: 1
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
en:
  languageCode: en-US
  languageName: "English"
  contentDir: content/en
  title: English Website by rosoefox
  weight: 2
  params:
    description: Site description in English
  menu:
    main:
      - name: 영어소개
        url: '#about'
        weight: 1
      - name : 경험티비
        url: 'experience/'
        weight: 2

